# Promote a box-sized verify page to a full-canvas one.
#
#   python3 _ref/mkfull.py <part>.verify.html <refX> <refY>
#     -> writes <part>.verify-full.html beside it
#
# A verify page sized to its own box does not rasterise the way the real canvas
# does: Chrome resolves a fractionally-sized box — especially one carrying a
# clip-path — against the enclosing stage, so stage width alone shifts the pixel
# grid. See ANATOMY.md, "The stage width changes the pixels".
#
# This rewrites the page so the stage is the canvas's own 1292x635 and the part
# sits at its TRUE canvas position, nudged there by an integer-offset wrapper.
# Fractional edges then land on exactly the grid the reference was rendered on.
#
# Gate the result with the matching flag:
#   python3 _ref/check.py <part>.verify-full.html <W> <H> <refX> <refY> --full
#
# Measured effect across all five loose parts: every one moves to mean 0.000 /
# max 0. The residuals the box-sized pages reported (0.082 chip, 0.064 conduit,
# 0.288 panel frame, 0.114 display plate) were the harness, not the parts.
import re
import sys

FULL_W, FULL_H = 1292, 635


def main():
    if len(sys.argv) < 4:
        sys.exit('usage: mkfull.py <part>.verify.html <refX> <refY>')
    src, rx, ry = sys.argv[1], int(float(sys.argv[2])), int(float(sys.argv[3]))
    out = re.sub(r'\.verify\.html$', '.verify-full.html', src)
    if out == src:
        sys.exit('expected a *.verify.html page')

    html = open(src).read()
    m = re.search(r'(<div class="stage"[^>]*>)(.*?)(</div>\s*</body>)', html, re.S)
    if not m:
        sys.exit('no <div class="stage"> ... </div></body> found in ' + src)
    _, inner, tail = m.groups()

    # width:0;height:0 on the wrapper keeps it out of the part's own layout —
    # every part sizes itself explicitly, so nothing resolves against it.
    block = (f'<div class="stage" style="width:{FULL_W}px;height:{FULL_H}px">'
             f'<div style="position:absolute;left:{rx}px;top:{ry}px;width:0;height:0">'
             + inner + '</div>' + tail)

    banner = (f'<!-- GENERATED by _ref/mkfull.py from {src.split("/")[-1]} — do not hand-edit.\n'
              f'     Full-canvas verify page: the part sits at its true canvas position\n'
              f'     ({rx}, {ry}) inside the real {FULL_W}x{FULL_H} stage, so it rasterises on\n'
              f'     the same pixel grid as the reference. Gate it with check.py --full. -->\n')

    open(out, 'w').write(html[:m.start()] + banner + block + html[m.end():])
    print('wrote', out)


main()
